### PR TITLE
logentries_install.sh: Fix the system log issue. Add gentoo support.

### PR DESCRIPTION
**Pull request by boykom**
* Fix the system log issue (Fedora 19, 20 also is supported).
* Add Gentoo support. 
* Some refactoring

### CODE REVIEW

**Comment by vilda** [comment]
Thanks @boykom and sorry for late response.

Can you have a look @StephenHynes7 if that's OK? We may need to do some additional testing.

**Comment by geekle** [comment]
Will this include an ebuild too?

**Comment by vilda** [comment]
Thanks @boykom

**Comment by vilda** [comment]
I'm not sure @geekle As I'm not Gentoo experts I relay on community here

**Comment by vilda** [comment]
Merged manually

**Pull request closed without merging**
