### PR TITLE
Adding support for Ubuntu 15.04 (Vivid Vervet)

### PR DESCRIPTION
**Pull request by vilda**

### CODE REVIEW

**Comment by vilda** [comment]
Can you have a look @mrud ?

**Comment by mrud** [comment]
should we change the gpg import to use port 80?

**Comment by vilda** [comment]
Let me update it...

**Comment by vilda** [comment]
Done - is it ok now @mrud ?

**Comment by mrud** [comment]
+1, yes lgtm sorry for the delay

**Pull request merged**
