### PR TITLE
Remove v1 stats api

### PR DESCRIPTION
**Pull request by StephenHynes7**
This removes the v1 stats api since the UI is no longer using these metrics. We will instead encourage people to use the Metrics feature of the agent.

### CODE REVIEW

**Comment by StephenHynes7** [comment]
@vilda-r7 @udangel-r7 take a look?

**Comment by vilda-r7** [comment]
Have you run tests @StephenHynes7 ?

**Comment by StephenHynes7** [comment]
No, let me do that and get back to you.

**Comment by vilda-r7** [comment]
Perfect, just to make sure it does not need any updates

**Comment by dtracey-r7** [comment]
LGTM +1 
Also, need to remove from Windows agent (and I'm checking stories for leserver - will return 200 and ok on receiving push_wl from legacy agents)

**Comment by StephenHynes7** [comment]
@vilda-r7  @pclune-r7  ran the tests for me which came back green so we should be good!

**Pull request merged**
