### PR TITLE
install python formats for Mac users

### PR DESCRIPTION
**Pull request by StephenHynes7**
Install python formats as it is a required dependency

### CODE REVIEW

**Comment by StephenHynes7** [comment]
@vilda @mrud can you take a look?

Reference to the issue can be found here http://stackoverflow.com/questions/32782751/cannot-install-logentries-mac-agent-on-os-x-yosemite

**Comment by mrud** [comment]
I don't think this is correct as it should use the file from `src` ?

**Comment by StephenHynes7** [comment]
@mrud Can you clarify?

**Comment by mrud** [comment]
The import formats is not about the module you installed via `pip` but about the file in the `src` folder. So this file should get downloaded instead

**Comment by StephenHynes7** [comment]
Hmm looking closely it looks like we are pulling each source file individually, going to fix this up.

**Pull request closed without merging**
